### ISSUE TITLE
Incorrect indexing in the README example

### ISSUE THREAD

**Issue by mannatsingh** [google-research/reassessed-imagenet#2]
In the `README`, `real_labels = {f'ILSVRC2012_val_{i:08d}.JPEG': labels for i, labels in enumerate(json.load('real.json'))}` should be changed to `real_labels = {f'ILSVRC2012_val_{i + 1:08d}.JPEG': labels for i, labels in enumerate(json.load('real.json'))}` since the numbering starts from 1 and not 0.

**Comment by lucasb-eyer** [comment]
Thanks for letting us know and sorry for the delay. Fixed in #1
